version: 2.1
orbs:
  architect: giantswarm/architect@4.30.1

workflows:
  test-and-push:
    jobs:
      - architect/push-to-docker:
          context: architect
          name: push-tekton-dashboard-loki-proxy-to-quay
          image: "quay.io/giantswarm/tekton-dashboard-loki-proxy"
          username_envar: "QUAY_USERNAME"
          password_envar: "QUAY_PASSWORD"
          filters:
            # Trigger the job also on git tag.
            tags:
              only: /^v.*/
      - architect/push-to-docker:
          context: "architect"
          name: push-tekton-dashboard-loki-proxy-to-docker
          image: "docker.io/giantswarm/tekton-dashboard-loki-proxy"
          username_envar: "DOCKER_USERNAME"
          password_envar: "DOCKER_PASSWORD"
          # Needed to trigger job also on git tag.
          filters:
            tags:
              only: /^v.*/

  package-and-push-chart-on-tag:
    jobs:
      - architect/push-to-app-catalog:
          context: "architect"
          # executor: "app-build-suite" # uncomment this if you want automatic metadata generation and helm chart linting
          name: "package and push tekton-dashboard-loki-proxy chart"
          app_catalog: "giantswarm-catalog"
          app_catalog_test: "giantswarm-test-catalog"
          chart: "tekton-dashboard-loki-proxy"
          # Trigger job on git tag.
          filters:
            tags:
              only: /^v.*/
