name: tekton-dashboard-loki-proxy
serviceType: managed

project:
  branch: "[[ .Branch ]]"
  commit: "[[ .SHA ]]"

image:
  registry: quay.io
  name: giantswarm/tekton-dashboard-loki-proxy
  tag: v0.0.1
  pullPolicy: IfNotPresent
